"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.taskRouter = void 0;
const express_1 = __importDefault(require("express"));
const task_controller_1 = require("../controller/task.controller");
// import { deserializeUser } from "../middleware/deserializeUser";
const findTask_middleware_1 = require("../middleware/findTask.middleware");
// import { requireUser } from "../middleware/requireUser";
const router = express_1.default.Router();
exports.taskRouter = router;
//router.use(deserializeUser, requireUser);
router.post("/api/task", task_controller_1.createTaskHandler);
router.get("/api/task/:_id", task_controller_1.getTaskHandler);
router.patch("/api/task/:_id", findTask_middleware_1.findTaskMiddleware, task_controller_1.editTaskHandler);
router.delete("/api/task/:_id", findTask_middleware_1.findTaskMiddleware, task_controller_1.deleteTaskHandler);
router.get("/api/tasks/manager/:_id", [], task_controller_1.getTasksHandler);
router.get("/api/tasks/employee/:email", [], task_controller_1.getEmployeeTasksHandler);
